# Generated by Django 4.2.2 on 2023-06-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
